// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxkihXXNNdq8jsXuF8VOSFkDlvWeAfGwc',
    appId: '1:720592513771:ios:5f6c732309bfc25d6e2cae',
    messagingSenderId: '720592513771',
    projectId: 'examroadmaptrackerap-49c86e37',
    storageBucket: 'examroadmaptrackerap-49c86e37.firebasestorage.app',
    iosBundleId: 'com.example.stockMarketMonitoringApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASNTnfcEdmhr5jHdGCQAtrBnn6uiXFs7s',
    appId: '1:720592513771:android:b228123894f400416e2cae',
    messagingSenderId: '720592513771',
    projectId: 'examroadmaptrackerap-49c86e37',
    storageBucket: 'examroadmaptrackerap-49c86e37.firebasestorage.app',
  );
}
